.TH "libsocket::dgram_client_socket" 3 "Sat Mar 2 2013" "libsocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libsocket::dgram_client_socket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dgramclient\&.hpp>\fP
.PP
Inherits \fBlibsocket::socket\fP\&.
.PP
Inherited by \fBlibsocket::inet_dgram_client\fP, and \fBlibsocket::unix_dgram_client\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ssize_t \fBsnd\fP (const void *buf, size_t len, int flags=0)"
.br
.ti -1c
.RI "ssize_t \fBrcv\fP (void *buf, size_t len, int flags=0)"
.br
.ti -1c
.RI "bool \fBgetconn\fP (void) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBconnected\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBdgram_client_socket\fP & \fBoperator<<\fP (\fBdgram_client_socket\fP &sock, const char *str)"
.br
.ti -1c
.RI "\fBdgram_client_socket\fP & \fBoperator<<\fP (\fBdgram_client_socket\fP &sock, string &str)"
.br
.ti -1c
.RI "\fBdgram_client_socket\fP & \fBoperator>>\fP (\fBdgram_client_socket\fP &sock, string &dest)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents generic datagram socket\&. 
.SH "Member Function Documentation"
.PP 
.SS "ssize_t libsocket::dgram_client_socket::rcv (void *buf, size_tlen, intflags = \fC0\fP)"

.PP
Receive data from a connected DGRAM socket\&. If a datagram socket is connected, this function may be called to receive data sent from the host connected to\&.
.PP
\fBParameters:\fP
.RS 4
\fIbuf\fP Area to write the data to 
.br
\fIlen\fP How many data we want to receive 
.br
\fIflags\fP Flags to be passed to \fCrecv(2)\fP
.RE
.PP
\fBReturn values:\fP
.RS 4
\fI>0\fP n bytes were received\&. 
.br
\fI0\fP 0 bytes were received\&. (EOF?) 
.br
\fI-1\fP Something went wrong\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libsocket from the source code\&.
