.TH "libsocket::inet_socket" 3 "Sat Mar 2 2013" "libsocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libsocket::inet_socket \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBlibsocket::socket\fP\&.
.PP
Inherited by \fBlibsocket::inet_dgram\fP, \fBlibsocket::inet_stream\fP, and \fBlibsocket::inet_stream_server\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBgethost\fP (void) const "
.br
.ti -1c
.RI "string \fBgetport\fP (void) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "string \fBhost\fP"
.br
.ti -1c
.RI "string \fBport\fP"
.br
.ti -1c
.RI "int \fBproto\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for libsocket from the source code\&.
