.TH "C++/socket.cpp" 3 "Sat Mar 2 2013" "libsocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C++/socket.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <unistd\&.h>\fP
.br
\fC#include '\&.\&./headers/socket\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
Provides the basic socket functionality, like a field for the file descriptor and the destructor respectively a close()-wrapper destroy()\&. This is the root of the class graph\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsocket from the source code\&.
