.TH "headers/socket.hpp" 3 "Sat Mar 2 2013" "libsocket" \" -*- nroff -*-
.ad l
.nh
.SH NAME
headers/socket.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include 'exception\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBlibsocket::socket\fP"
.br
.RI "\fIsocket is the base class of every other libsocket++ object\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The base class's header file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libsocket from the source code\&.
